
# cargo-vet audits file

[[audits.axum-auth]]
who = "MTRNord <mtrnord1@gmail.com>"
criteria = "safe-to-deploy"
version = "0.3.0"
notes = "Only extracts headers and does basic splitting. No unsafe code and seems sane"

[[audits.openssl-sys]]
who = "MTRNord <mtrnord1@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.9.75 -> 0.9.76"
notes = "Only touches code we dont use. Safe fur us."

[[audits.tokio]]
who = "MTRNord <mtrnord1@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.21.1 -> 1.21.2"
notes = "Removes a dependecy and inlines it. Code seems simple enough and has safety explained. Looks sane."

