
# cargo-vet config file

[imports.bytecodealliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[[exemptions.addr2line]]
criteria = "safe-to-deploy"
version = "0.17.0"

[[exemptions.adler]]
criteria = "safe-to-deploy"
version = "1.0.2"

[[exemptions.aes]]
criteria = "safe-to-deploy"
version = "0.7.5"

[[exemptions.stfu8]]
criteria = "safe-to-deploy"
version = "0.2.5"

[[exemptions.unicode-segmentation]]
criteria = "safe-to-deploy"
version = "1.10.0"

[[exemptions.ansi_term]]
criteria = "safe-to-deploy"
version = "0.12.1"

[[exemptions.async-trait]]
criteria = "safe-to-deploy"
version = "0.1.57"

[[exemptions.autocfg]]
criteria = "safe-to-deploy"
version = "1.1.0"

[[exemptions.axum]]
criteria = "safe-to-deploy"
version = "0.5.16"

[[exemptions.axum-core]]
criteria = "safe-to-deploy"
version = "0.2.8"

[[exemptions.backtrace]]
criteria = "safe-to-deploy"
version = "0.3.66"

[[exemptions.base64]]
criteria = "safe-to-deploy"
version = "0.13.0"

[[exemptions.base64ct]]
criteria = "safe-to-deploy"
version = "1.0.1"

[[exemptions.bitflags]]
criteria = "safe-to-deploy"
version = "1.3.2"

[[exemptions.block-buffer]]
criteria = "safe-to-deploy"
version = "0.10.3"

[[exemptions.byteorder]]
criteria = "safe-to-deploy"
version = "1.4.3"

[[exemptions.bytes]]
criteria = "safe-to-deploy"
version = "1.2.1"

[[exemptions.bzip2]]
criteria = "safe-to-deploy"
version = "0.4.3"

[[exemptions.bzip2-sys]]
criteria = "safe-to-deploy"
version = "0.1.11+1.0.8"

[[exemptions.cc]]
criteria = "safe-to-deploy"
version = "1.0.73"

[[exemptions.cfg-if]]
criteria = "safe-to-deploy"
version = "1.0.0"

[[exemptions.cipher]]
criteria = "safe-to-deploy"
version = "0.3.0"

[[exemptions.color-eyre]]
criteria = "safe-to-deploy"
version = "0.6.2"

[[exemptions.color-spantrace]]
criteria = "safe-to-deploy"
version = "0.2.0"

[[exemptions.constant_time_eq]]
criteria = "safe-to-deploy"
version = "0.1.5"

[[exemptions.cpufeatures]]
criteria = "safe-to-deploy"
version = "0.2.5"

[[exemptions.crc]]
criteria = "safe-to-deploy"
version = "2.1.0"

[[exemptions.crc-catalog]]
criteria = "safe-to-deploy"
version = "1.1.1"

[[exemptions.crc32fast]]
criteria = "safe-to-deploy"
version = "1.3.2"

[[exemptions.crossbeam-utils]]
criteria = "safe-to-deploy"
version = "0.8.11"

[[exemptions.crypto-common]]
criteria = "safe-to-deploy"
version = "0.1.6"

[[exemptions.curl]]
criteria = "safe-to-deploy"
version = "0.4.44"

[[exemptions.curl-sys]]
criteria = "safe-to-deploy"
version = "0.4.56+curl-7.83.1"

[[exemptions.digest]]
criteria = "safe-to-deploy"
version = "0.10.5"

[[exemptions.dyn-clone]]
criteria = "safe-to-run"
version = "1.0.9"

[[exemptions.eyre]]
criteria = "safe-to-deploy"
version = "0.6.8"

[[exemptions.filetime]]
criteria = "safe-to-deploy"
version = "0.2.17"

[[exemptions.flate2]]
criteria = "safe-to-deploy"
version = "1.0.24"

[[exemptions.fnv]]
criteria = "safe-to-deploy"
version = "1.0.7"

[[exemptions.form_urlencoded]]
criteria = "safe-to-deploy"
version = "1.1.0"

[[exemptions.futures-channel]]
criteria = "safe-to-deploy"
version = "0.3.24"

[[exemptions.futures-core]]
criteria = "safe-to-deploy"
version = "0.3.24"

[[exemptions.futures-task]]
criteria = "safe-to-deploy"
version = "0.3.24"

[[exemptions.futures-util]]
criteria = "safe-to-deploy"
version = "0.3.24"

[[exemptions.generic-array]]
criteria = "safe-to-deploy"
version = "0.14.6"

[[exemptions.gimli]]
criteria = "safe-to-deploy"
version = "0.26.2"

[[exemptions.half]]
criteria = "safe-to-deploy"
version = "1.8.2"

[[exemptions.hermit-abi]]
criteria = "safe-to-deploy"
version = "0.1.19"

[[exemptions.hmac]]
criteria = "safe-to-deploy"
version = "0.12.1"

[[exemptions.http]]
criteria = "safe-to-deploy"
version = "0.2.8"

[[exemptions.http-body]]
criteria = "safe-to-deploy"
version = "0.4.5"

[[exemptions.http-range-header]]
criteria = "safe-to-deploy"
version = "0.3.0"

[[exemptions.httparse]]
criteria = "safe-to-deploy"
version = "1.8.0"

[[exemptions.httpdate]]
criteria = "safe-to-deploy"
version = "1.0.2"

[[exemptions.hyper]]
criteria = "safe-to-deploy"
version = "0.14.20"

[[exemptions.indenter]]
criteria = "safe-to-deploy"
version = "0.3.3"

[[exemptions.itoa]]
criteria = "safe-to-deploy"
version = "1.0.3"

[[exemptions.jobserver]]
criteria = "safe-to-deploy"
version = "0.1.25"

[[exemptions.lazy_static]]
criteria = "safe-to-deploy"
version = "1.4.0"

[[exemptions.libc]]
criteria = "safe-to-deploy"
version = "0.2.133"

[[exemptions.libz-sys]]
criteria = "safe-to-deploy"
version = "1.1.8"

[[exemptions.lock_api]]
criteria = "safe-to-deploy"
version = "0.4.9"

[[exemptions.log]]
criteria = "safe-to-deploy"
version = "0.4.17"

[[exemptions.matchers]]
criteria = "safe-to-deploy"
version = "0.1.0"

[[exemptions.matchit]]
criteria = "safe-to-deploy"
version = "0.5.0"

[[exemptions.memchr]]
criteria = "safe-to-deploy"
version = "2.5.0"

[[exemptions.mime]]
criteria = "safe-to-deploy"
version = "0.3.16"

[[exemptions.miniz_oxide]]
criteria = "safe-to-deploy"
version = "0.5.4"

[[exemptions.mio]]
criteria = "safe-to-deploy"
version = "0.8.4"

[[exemptions.num-complex]]
criteria = "safe-to-deploy"
version = "0.4.2"

[[exemptions.num-traits]]
criteria = "safe-to-deploy"
version = "0.2.15"

[[exemptions.num_cpus]]
criteria = "safe-to-deploy"
version = "1.13.1"

[[exemptions.num_threads]]
criteria = "safe-to-deploy"
version = "0.1.6"

[[exemptions.object]]
criteria = "safe-to-deploy"
version = "0.29.0"

[[exemptions.once_cell]]
criteria = "safe-to-deploy"
version = "1.15.0"

[[exemptions.opaque-debug]]
criteria = "safe-to-deploy"
version = "0.3.0"

[[exemptions.openssl-probe]]
criteria = "safe-to-deploy"
version = "0.1.5"

[[exemptions.openssl-sys]]
criteria = "safe-to-deploy"
version = "0.9.75"

[[exemptions.owo-colors]]
criteria = "safe-to-deploy"
version = "3.5.0"

[[exemptions.parking_lot]]
criteria = "safe-to-deploy"
version = "0.12.1"

[[exemptions.parking_lot_core]]
criteria = "safe-to-deploy"
version = "0.9.3"

[[exemptions.password-hash]]
criteria = "safe-to-deploy"
version = "0.3.2"

[[exemptions.pbkdf2]]
criteria = "safe-to-deploy"
version = "0.10.1"

[[exemptions.percent-encoding]]
criteria = "safe-to-deploy"
version = "2.2.0"

[[exemptions.pin-project]]
criteria = "safe-to-deploy"
version = "1.0.12"

[[exemptions.pin-project-internal]]
criteria = "safe-to-deploy"
version = "1.0.12"

[[exemptions.pin-project-lite]]
criteria = "safe-to-deploy"
version = "0.2.9"

[[exemptions.pin-utils]]
criteria = "safe-to-deploy"
version = "0.1.0"

[[exemptions.pkg-config]]
criteria = "safe-to-deploy"
version = "0.3.25"

[[exemptions.proc-macro2]]
criteria = "safe-to-deploy"
version = "1.0.44"

[[exemptions.protobuf]]
criteria = "safe-to-deploy"
version = "2.27.1"

[[exemptions.quote]]
criteria = "safe-to-deploy"
version = "1.0.21"

[[exemptions.rand_core]]
criteria = "safe-to-deploy"
version = "0.6.4"

[[exemptions.redox_syscall]]
criteria = "safe-to-deploy"
version = "0.2.16"

[[exemptions.regex]]
criteria = "safe-to-deploy"
version = "1.6.0"

[[exemptions.regex-automata]]
criteria = "safe-to-deploy"
version = "0.1.10"

[[exemptions.regex-syntax]]
criteria = "safe-to-deploy"
version = "0.6.27"

[[exemptions.rustc-demangle]]
criteria = "safe-to-deploy"
version = "0.1.21"

[[exemptions.rustversion]]
criteria = "safe-to-deploy"
version = "1.0.9"

[[exemptions.ryu]]
criteria = "safe-to-deploy"
version = "1.0.11"

[[exemptions.schannel]]
criteria = "safe-to-deploy"
version = "0.1.20"

[[exemptions.schemars]]
criteria = "safe-to-run"
version = "0.8.10"

[[exemptions.schemars_derive]]
criteria = "safe-to-run"
version = "0.8.10"

[[exemptions.scopeguard]]
criteria = "safe-to-deploy"
version = "1.1.0"

[[exemptions.semver]]
criteria = "safe-to-deploy"
version = "1.0.14"

[[exemptions.serde]]
criteria = "safe-to-deploy"
version = "1.0.145"

[[exemptions.serde_derive]]
criteria = "safe-to-deploy"
version = "1.0.145"

[[exemptions.serde_derive_internals]]
criteria = "safe-to-run"
version = "0.26.0"

[[exemptions.serde_json]]
criteria = "safe-to-deploy"
version = "1.0.85"

[[exemptions.serde_urlencoded]]
criteria = "safe-to-deploy"
version = "0.7.1"

[[exemptions.sha1]]
criteria = "safe-to-deploy"
version = "0.10.5"

[[exemptions.sha2]]
criteria = "safe-to-deploy"
version = "0.10.6"

[[exemptions.sharded-slab]]
criteria = "safe-to-deploy"
version = "0.1.4"

[[exemptions.signal-hook-registry]]
criteria = "safe-to-deploy"
version = "1.4.0"

[[exemptions.smallvec]]
criteria = "safe-to-deploy"
version = "1.9.0"

[[exemptions.socket2]]
criteria = "safe-to-deploy"
version = "0.4.7"

[[exemptions.subtle]]
criteria = "safe-to-deploy"
version = "2.4.1"

[[exemptions.syn]]
criteria = "safe-to-deploy"
version = "1.0.101"

[[exemptions.sync_wrapper]]
criteria = "safe-to-deploy"
version = "0.1.1"

[[exemptions.tar]]
criteria = "safe-to-deploy"
version = "0.4.38"

[[exemptions.tensorflow]]
criteria = "safe-to-deploy"
version = "0.19.1"

[[exemptions.tensorflow-internal-macros]]
criteria = "safe-to-deploy"
version = "0.0.3"

[[exemptions.tensorflow-sys]]
criteria = "safe-to-deploy"
version = "0.22.1"

[[exemptions.thread_local]]
criteria = "safe-to-deploy"
version = "1.1.4"

[[exemptions.time]]
criteria = "safe-to-deploy"
version = "0.3.14"

[[exemptions.time-macros]]
criteria = "safe-to-deploy"
version = "0.2.4"

[[exemptions.tokio]]
criteria = "safe-to-deploy"
version = "1.21.1"

[[exemptions.tokio-macros]]
criteria = "safe-to-deploy"
version = "1.8.0"

[[exemptions.tower]]
criteria = "safe-to-deploy"
version = "0.4.13"

[[exemptions.tower-http]]
criteria = "safe-to-deploy"
version = "0.3.4"

[[exemptions.tower-layer]]
criteria = "safe-to-deploy"
version = "0.3.1"

[[exemptions.tower-service]]
criteria = "safe-to-deploy"
version = "0.3.2"

[[exemptions.tracing]]
criteria = "safe-to-deploy"
version = "0.1.36"

[[exemptions.tracing-attributes]]
criteria = "safe-to-deploy"
version = "0.1.22"

[[exemptions.tracing-core]]
criteria = "safe-to-deploy"
version = "0.1.29"

[[exemptions.tracing-error]]
criteria = "safe-to-deploy"
version = "0.2.0"

[[exemptions.tracing-log]]
criteria = "safe-to-deploy"
version = "0.1.3"

[[exemptions.tracing-subscriber]]
criteria = "safe-to-deploy"
version = "0.3.15"

[[exemptions.try-lock]]
criteria = "safe-to-deploy"
version = "0.2.3"

[[exemptions.typenum]]
criteria = "safe-to-deploy"
version = "1.15.0"

[[exemptions.unicode-ident]]
criteria = "safe-to-deploy"
version = "1.0.4"

[[exemptions.valuable]]
criteria = "safe-to-deploy"
version = "0.1.0"

[[exemptions.vcpkg]]
criteria = "safe-to-deploy"
version = "0.2.15"

[[exemptions.version_check]]
criteria = "safe-to-deploy"
version = "0.9.4"

[[exemptions.want]]
criteria = "safe-to-deploy"
version = "0.3.0"

[[exemptions.wasi]]
criteria = "safe-to-deploy"
version = "0.11.0+wasi-snapshot-preview1"

[[exemptions.winapi]]
criteria = "safe-to-deploy"
version = "0.3.9"

[[exemptions.winapi-i686-pc-windows-gnu]]
criteria = "safe-to-deploy"
version = "0.4.0"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
criteria = "safe-to-deploy"
version = "0.4.0"

[[exemptions.windows-sys]]
criteria = "safe-to-deploy"
version = "0.36.1"

[[exemptions.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
version = "0.36.1"

[[exemptions.windows_i686_gnu]]
criteria = "safe-to-deploy"
version = "0.36.1"

[[exemptions.windows_i686_msvc]]
criteria = "safe-to-deploy"
version = "0.36.1"

[[exemptions.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
version = "0.36.1"

[[exemptions.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
version = "0.36.1"

[[exemptions.xattr]]
criteria = "safe-to-deploy"
version = "0.2.3"

[[exemptions.zip]]
criteria = "safe-to-deploy"
version = "0.6.2"

[[exemptions.zstd]]
criteria = "safe-to-deploy"
version = "0.10.2+zstd.1.5.2"

[[exemptions.zstd-safe]]
criteria = "safe-to-deploy"
version = "4.1.6+zstd.1.5.2"

[[exemptions.zstd-sys]]
criteria = "safe-to-deploy"
version = "1.6.3+zstd.1.5.2"
